"""
3D Model Export Service — glTF and IFC export for design visualization.

Generates standardized 3D model files from CanonicalDesignVersion data:
  - glTF 2.0 (JSON + binary) — for web viewers, Three.js, Blender
  - IFC (Industry Foundation Classes) — for BIM software

This module generates the data structures; actual binary encoding
would be done by dedicated libraries (pygltflib, ifcopenshell).
"""
from __future__ import annotations

import json
import math
from typing import Any


def export_gltf_scene(
    design: dict[str, Any],
    material_colors: dict[str, dict[str, float]] | None = None,
) -> dict[str, Any]:
    """
    Export a design as a glTF 2.0 scene (JSON structure).

    Args:
        design: CanonicalDesignVersion dict.
        material_colors: Optional material_id -> RGB color mapping.

    Returns:
        glTF 2.0 JSON scene structure.
    """
    if material_colors is None:
        material_colors = {
            "treated_bamboo": {"r": 0.55, "g": 0.73, "b": 0.27},  # Green
            "reclaimed_timber": {"r": 0.60, "g": 0.40, "b": 0.20},  # Brown
            "stabilized_mud_brick": {"r": 0.76, "g": 0.60, "b": 0.42},  # Sand
            "corrugated_tin": {"r": 0.70, "g": 0.70, "b": 0.72},  # Silver
            "steel_connector": {"r": 0.40, "g": 0.40, "b": 0.42},  # Dark grey
        }

    default_color = {"r": 0.5, "g": 0.5, "b": 0.5}

    # Build mesh data for each member
    meshes = []
    materials = []
    accessors = []
    buffer_views = []
    nodes = []

    # Create materials
    material_ids_used = set()
    for member in design.get("members", []):
        mat_id = member.get("material_id", "unknown")
        if mat_id not in material_ids_used:
            material_ids_used.add(mat_id)
            color = material_colors.get(mat_id, default_color)
            materials.append({
                "name": mat_id,
                "pbrMetallicRoughness": {
                    "baseColorFactor": [color["r"], color["g"], color["b"], 1.0],
                    "metallicFactor": 0.1,
                    "roughnessFactor": 0.8,
                },
            })

    material_index_map = {mid: i for i, mid in enumerate(material_ids_used)}

    # Create meshes for each member (cylindrical representation)
    for i, member in enumerate(design.get("members", [])):
        start = member.get("start", {})
        end = member.get("end", {})
        diameter = member.get("diameter_m", 0.10)
        mat_id = member.get("material_id", "unknown")
        mat_idx = material_index_map.get(mat_id, 0)

        # Generate cylinder vertices (8 segments)
        segments = 8
        radius = diameter / 2.0
        sx = start.get("x_m", 0)
        sy = start.get("y_m", 0)
        sz = start.get("z_m", 0)
        ex = end.get("x_m", 0)
        ey = end.get("y_m", 0)
        ez = end.get("z_m", 0)

        # Create a simple line representation for the member
        mesh = {
            "name": member.get("id", f"member_{i}"),
            "primitives": [
                {
                    "attributes": {
                        "POSITION": len(accessors),
                    },
                    "material": mat_idx,
                    "mode": 3,  # LINE_STRIP (simplified) — would be 4 (TRIANGLES) for full mesh
                }
            ],
        }
        meshes.append(mesh)

    # Build glTF structure
    gltf = {
        "asset": {
            "version": "2.0",
            "generator": "Panagah Model Export v1.0",
            "copyright": "Generated by Panagah Humanitarian Shelter Design Platform",
        },
        "scene": 0,
        "scenes": [
            {
                "name": design.get("version", "Design"),
                "nodes": list(range(len(design.get("members", [])))),
            }
        ],
        "nodes": [
            {
                "name": member.get("id", f"member_{i}"),
                "mesh": i,
            }
            for i, member in enumerate(design.get("members", []))
        ],
        "meshes": meshes,
        "materials": materials if materials else [{"name": "default", "pbrMetallicRoughness": {"baseColorFactor": [0.5, 0.5, 0.5, 1.0]}}],
    }

    return gltf


def export_ifc_structure(
    design: dict[str, Any],
    project_name: str = "Panagah Shelter",
    site_name: str = "Project Site",
) -> dict[str, Any]:
    """
    Export a design as IFC structure data.

    Returns an IFC-compatible data structure (JSON representation).
    In production, use ifcopenshell to generate actual .ifc files.
    """
    ifc_data = {
        "header": {
            "file_description": "IFC2X3 Model exported from Panagah",
            "file_name": f"{project_name}.ifc",
            "originating_system": "Panagah API v1.0",
        },
        "project": {
            "name": project_name,
            "description": "Humanitarian shelter structural design",
        },
        "site": {
            "name": site_name,
            "description": "Project construction site",
        },
        "building": {
            "name": f"{project_name} Building",
            "building_storeys": [
                {
                    "name": "Ground Floor",
                    "elevation": 0.0,
                }
            ],
        },
        "structural_members": [],
        "connections": [],
        "materials": [],
    }

    # Map members to IFC elements
    for member in design.get("members", []):
        member_type = member.get("type", "beam")
        ifc_class = {
            "beam": "IfcBeam",
            "column": "IfcColumn",
            "brace": "IfcMember",
            "rafter": "IfcBeam",
            "panel": "IfcPlate",
            "connector": "IfcFastener",
        }.get(member_type, "IfcMember")

        start = member.get("start", {})
        end = member.get("end", {})

        ifc_data["structural_members"].append({
            "ifc_class": ifc_class,
            "global_id": f"0_{member.get('id', 'unknown')}",
            "name": member.get("id", "unknown"),
            "material": member.get("material_id", "unknown"),
            "length_m": member.get("length_m", 0),
            "cross_section": {
                "shape": "circular",
                "diameter_m": member.get("diameter_m", 0.10),
            },
            "start_point": {
                "x": start.get("x_m", 0),
                "y": start.get("y_m", 0),
                "z": start.get("z_m", 0),
            },
            "end_point": {
                "x": end.get("x_m", 0),
                "y": end.get("y_m", 0),
                "z": end.get("z_m", 0),
            },
        })

    # Map connections
    for conn in design.get("connections", []):
        ifc_data["connections"].append({
            "global_id": f"0_{conn.get('id', 'unknown')}",
            "name": conn.get("id", "unknown"),
            "type": conn.get("type", "bolted"),
            "member_a": conn.get("a", ""),
            "member_b": conn.get("b", ""),
        })

    return ifc_data


def export_obj_mesh(
    design: dict[str, Any],
    material_colors: dict[str, dict[str, float]] | None = None,
) -> str:
    """
    Export a design as OBJ mesh (text format).

    Returns OBJ file content as string.
    """
    if material_colors is None:
        material_colors = {
            "treated_bamboo": {"r": 0.55, "g": 0.73, "b": 0.27},
            "reclaimed_timber": {"r": 0.60, "g": 0.40, "b": 0.20},
        }

    lines = [f"# Panagah OBJ Export — {design.get('version', 'Design')}", ""]
    vertex_offset = 0

    # MTL file reference
    lines.append("mtllib materials.mtl")
    lines.append("")

    for member in design.get("members", []):
        start = member.get("start", {})
        end = member.get("end", {})
        diameter = member.get("diameter_m", 0.10)
        radius = diameter / 2.0
        segments = 8

        sx = start.get("x_m", 0)
        sy = start.get("y_m", 0)
        sz = start.get("z_m", 0)
        ex = end.get("x_m", 0)
        ey = end.get("y_m", 0)
        ez = end.get("z_m", 0)

        # Simple line representation
        lines.append(f"o {member.get('id', 'unknown')}")
        lines.append(f"usemtl {member.get('material_id', 'default')}")
        lines.append(f"v {sx} {sy} {sz}")
        lines.append(f"v {ex} {ey} {ez}")
        lines.append(f"l {vertex_offset + 1} {vertex_offset + 2}")
        lines.append("")
        vertex_offset += 2

    return "\n".join(lines)
