"""
PDF Report Generator — Professional Engineering Calculation Report

Generates structured PDF reports with:
  - Project overview
  - Design specifications
  - Wind load calculations
  - Seismic load calculations
  - Structural analysis results
  - Compliance status
  - Cost estimation
  - Recommendations

Uses fpdf2 for PDF generation. No external dependencies beyond fpdf2.
"""
from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any

from fpdf import FPDF


class PanagahReport(FPDF):
    """Custom PDF class with PANAH branding."""

    def __init__(self, project_name: str = "Panagah"):
        super().__init__()
        self.project_name = project_name
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        # Header bar
        self.set_fill_color(12, 37, 42)  # #0C252A
        self.rect(0, 0, 210, 15, 'F')
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 4)
        self.cell(0, 7, f"PANAGAH  |  {self.project_name}", align="L")
        self.set_font("Helvetica", "", 8)
        self.set_xy(150, 4)
        self.cell(0, 7, datetime.now(timezone.utc).strftime("%Y-%m-%d"), align="R")
        self.ln(12)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  |  Generated by Panagah API  |  For prescreening only", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(12, 37, 42)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        # Underline
        self.set_draw_color(12, 37, 42)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def subsection_title(self, title: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(45, 106, 79)  # #2D6A4F
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(51, 51, 51)
        self.multi_cell(0, 5, text)
        self.ln(2)

    def key_value(self, key: str, value: str):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(51, 51, 51)
        self.cell(70, 6, key)
        self.set_font("Helvetica", "", 9)
        self.cell(0, 6, value, new_x="LMARGIN", new_y="NEXT")

    def table_header(self, columns: list[str], widths: list[float]):
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(12, 37, 42)
        self.set_text_color(255, 255, 255)
        for col, w in zip(columns, widths):
            self.cell(w, 7, col, border=1, align="C", fill=True)
        self.ln()

    def table_row(self, values: list[str], widths: list[float], fill: bool = False):
        self.set_font("Helvetica", "", 8)
        self.set_text_color(51, 51, 51)
        if fill:
            self.set_fill_color(234, 245, 249)  # Light blue tint
        for val, w in zip(values, widths):
            self.cell(w, 6, str(val), border=1, align="C", fill=fill)
        self.ln()

    def status_badge(self, status: str):
        if status == "pass":
            self.set_fill_color(64, 145, 108)  # Green
            label = "PASS"
        elif status == "fail":
            self.set_fill_color(200, 50, 50)  # Red
            label = "FAIL"
        else:
            self.set_fill_color(212, 163, 115)  # Amber
            label = "REVIEW"
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(255, 255, 255)
        w = self.get_string_width(label) + 8
        x = self.get_x()
        self.rect(x, self.get_y(), w, 7, 'F')
        self.cell(w, 7, label, align="C")
        self.ln(10)


def generate_engineering_report(
    project_name: str,
    design_data: dict[str, Any],
    wind_data: dict[str, Any] | None = None,
    seismic_data: dict[str, Any] | None = None,
    analysis_data: dict[str, Any] | None = None,
    compliance_data: dict[str, Any] | None = None,
    cost_data: dict[str, Any] | None = None,
) -> bytes:
    """
    Generate a professional PDF engineering report.

    Returns:
        PDF file as bytes.
    """
    pdf = PanagahReport(project_name)
    pdf.alias_nb_pages()
    pdf.add_page()

    # --- Cover / Project Overview ---
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(12, 37, 42)
    pdf.cell(0, 12, "Structural Engineering Report", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Project: {project_name}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, "Standard: Sphere Handbook V24.1 / ASCE 7-22", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # Warning
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(180, 50, 50)
    pdf.multi_cell(0, 4,
        "DISCLAIMER: This report is generated for prescreening purposes only. "
        "It does not replace a full site-specific engineering analysis by a licensed professional. "
        "All values are reference figures for the Sphere Handbook compliance assessment."
    )
    pdf.ln(4)

    # --- Design Specifications ---
    pdf.section_title("1. Design Specifications")
    if design_data:
        for key, val in design_data.items():
            label = key.replace("_", " ").title()
            pdf.key_value(f"{label}:", str(val))
    pdf.ln(3)

    # --- Wind Load Analysis ---
    if wind_data:
        pdf.section_title("2. Wind Load Analysis (ASCE 7-22)")
        params = wind_data.get("coefficients", {})
        pdf.subsection_title("2.1 Velocity Pressure")
        pdf.key_value("Basic Wind Speed:", f"{wind_data.get('wind_speed_m_s', 0)} m/s ({wind_data.get('wind_speed_kmh', 0)} km/h)")
        pdf.key_value("Velocity Pressure (qh):", f"{wind_data.get('velocity_pressure_pa', 0):.1f} Pa ({wind_data.get('velocity_pressure_kpa', 0):.3f} kPa)")
        pdf.key_value("Kz (height coefficient):", str(params.get("kz", "N/A")))
        pdf.key_value("Kzt (topographic factor):", str(params.get("kzt", "N/A")))
        pdf.key_value("Kd (directionality):", str(params.get("kd", "N/A")))
        pdf.key_value("Gust Effect Factor:", str(params.get("gust_effect_factor", "N/A")))
        pdf.ln(2)

        pdf.subsection_title("2.2 Design Pressures by Zone")
        zones = wind_data.get("zones", [])
        if zones:
            cols = ["Zone", "Surface", "+P (Pa)", "-P (Pa)", "Net (Pa)"]
            widths = [35, 25, 35, 35, 35]
            pdf.table_header(cols, widths)
            for i, z in enumerate(zones):
                pdf.table_row([
                    z.get("zone_name", ""),
                    z.get("surface", ""),
                    f"{z.get('positive_pa', 0):.1f}",
                    f"{z.get('negative_pa', 0):.1f}",
                    f"{z.get('net_pa', 0):.1f}",
                ], widths, fill=(i % 2 == 0))
        pdf.ln(2)

        pdf.subsection_title("2.3 Governing Pressure")
        pdf.key_value("Governing Pressure:", f"{wind_data.get('governing_pressure_pa', 0):.1f} Pa ({wind_data.get('governing_pressure_kpa', 0):.3f} kPa)")
        pdf.key_value("Governing Zone:", wind_data.get("governing_zone", "N/A"))
        pdf.ln(1)

        safety = wind_data.get("safety_assessment", {})
        pdf.key_value("Wind Resistance:", "YES" if safety.get("is_wind_resistant") else "NO")
        pdf.key_value("Safety Margin:", f"{safety.get('safety_margin', 0):.2f}x")
        pdf.body_text(f"Assessment: {safety.get('assessment', 'N/A')}")
        pdf.ln(2)

    # --- Seismic Load Analysis ---
    if seismic_data:
        pdf.section_title("3. Seismic Load Analysis (ASCE 7-22)")
        params = seismic_data.get("parameters", {})
        results = seismic_data.get("results", {})

        pdf.subsection_title("3.1 Seismic Parameters")
        pdf.key_value("Zone Factor (Z):", str(params.get("zone_factor_z", "N/A")))
        pdf.key_value("Spectral Acceleration (Ss):", str(params.get("spectral_acceleration_ss", "N/A")))
        pdf.key_value("Design Spectral (Sds):", str(params.get("design_sds", "N/A")))
        pdf.key_value("Response Modification (R):", str(params.get("response_modification_r", "N/A")))
        pdf.key_value("Fundamental Period:", f"{params.get('fundamental_period_s', 0):.3f} s")
        pdf.key_value("Seismic Coefficient (Cs):", str(params.get("seismic_response_coefficient_cs", "N/A")))
        pdf.ln(2)

        pdf.subsection_title("3.2 Results")
        pdf.key_value("Total Weight:", f"{results.get('total_weight_kn', 0):.1f} kN")
        pdf.key_value("Base Shear:", f"{results.get('base_shear_kn', 0):.1f} kN")
        pdf.key_value("Base Shear Coefficient:", f"{results.get('base_shear_coefficient', 0):.4f}")
        pdf.key_value("Max Lateral Force:", f"{results.get('max_lateral_force_kn', 0):.1f} kN")
        pdf.key_value("Max Overturning Moment:", f"{results.get('max_overturning_moment_knm', 0):.1f} kNm")
        pdf.ln(1)

        safety = seismic_data.get("safety_assessment", {})
        pdf.key_value("Seismic Design:", "YES" if safety.get("is_seismically_designed") else "NO")
        pdf.key_value("Safety Margin:", f"{safety.get('safety_margin', 0):.2f}x")
        pdf.body_text(f"Assessment: {safety.get('assessment', 'N/A')}")

    # --- Structural Analysis ---
    if analysis_data:
        pdf.add_page()
        pdf.section_title("4. Structural Analysis")
        findings = analysis_data.get("findings", [])
        if findings:
            cols = ["Code", "Severity", "Message"]
            widths = [25, 20, 130]
            pdf.table_header(cols, widths)
            for i, f in enumerate(findings):
                pdf.table_row([
                    f.get("code", ""),
                    f.get("severity", ""),
                    f.get("message", "")[:80],
                ], widths, fill=(i % 2 == 0))
        pdf.ln(3)

    # --- Compliance Status ---
    if compliance_data:
        pdf.section_title("5. Compliance Assessment")
        summary = compliance_data.get("summary", {})
        pdf.key_value("Overall Status:", compliance_data.get("status", "N/A").upper())
        pdf.key_value("Standard:", compliance_data.get("standard", "N/A"))
        pdf.key_value("Total Rules:", str(summary.get("total", 0)))
        pdf.key_value("Passed:", str(summary.get("pass", 0)))
        pdf.key_value("Review Required:", str(summary.get("review", 0)))
        pdf.key_value("Failed:", str(summary.get("fail", 0)))
        pdf.ln(3)

    # --- Cost Estimation ---
    if cost_data:
        pdf.section_title("6. Cost Estimation")
        summary = cost_data.get("summary", {})
        pdf.key_value("Total Cost:", f"USD {summary.get('total_cost_usd', 0):.2f}")
        pdf.key_value("Material Cost:", f"USD {summary.get('material_cost_usd', 0):.2f}")
        pdf.key_value("Labor Cost:", f"USD {summary.get('labor_cost_usd', 0):.2f}")
        pdf.key_value("Transport Cost:", f"USD {summary.get('transport_cost_usd', 0):.2f}")
        pdf.key_value("Contingency:", f"USD {summary.get('contingency_cost_usd', 0):.2f}")
        pdf.ln(1)
        pdf.key_value("Cost per Person:", f"USD {summary.get('cost_per_person_usd', 0):.2f}")
        pdf.key_value("Cost per m2:", f"USD {summary.get('cost_per_m2_usd', 0):.2f}")
        pdf.ln(3)

    # --- Recommendations ---
    pdf.add_page()
    pdf.section_title("7. Recommendations")
    pdf.body_text(
        "Based on the structural analysis, wind load, seismic load, and Sphere Handbook "
        "compliance assessment, the following recommendations are provided:"
    )
    recs = [
        "Ensure all connections are bolted or lashed per Sphere Handbook Sec 4.2",
        "Verify foundation type is suitable for local soil conditions",
        "Apply preservative treatment to all timber/bamboo members",
        "Install cross-bracing on all wall panels for lateral stability",
        "Use galvanized fasteners to prevent corrosion in humid environments",
        "Ensure minimum 2.0m interior clearance at all habitable points",
        "Provide adequate roof overhang (>=300mm) for rain protection",
    ]
    for i, rec in enumerate(recs, 1):
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(12, 37, 42)
        pdf.cell(8, 6, f"{i}.")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 51, 51)
        pdf.multi_cell(0, 5, rec)
        pdf.ln(1)

    # --- Signature block ---
    pdf.ln(10)
    pdf.set_draw_color(12, 37, 42)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, "This report was generated by the Panagah Automated Structural Assessment System.", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, "For prescreening and Sphere Handbook compliance assessment only.", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, "A licensed structural engineer must review and approve all designs before construction.", new_x="LMARGIN", new_y="NEXT")

    # Output
    output = io.BytesIO()
    pdf.output(output)
    return output.getvalue()
